project:
  type: website
  resources:
    - "public/**/*"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    # There are 3 types of navigation in Quarto:
    # 1. Top Navigation - navbar: - https://quarto.org/docs/websites/website-navigation.html#top-navigation
    # 2. Side Navigation (left of page content) - sidebar: - https://quarto.org/docs/websites/website-navigation.html#side-navigation
    # 3. On Page Navigation (right of page content) - toc: - https://quarto.org/docs/reference/formats/html.html#table-of-contents
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true
    jupyter: python3
    code-copy: true
    code-fold: true
    code-annotations: hover

website:
  title: "Bedrock"
  description: "Bedrock, the Open Source Foundation for Geotechnical Engineering"
  image: "public/Bedrock_inCircle.png"
  favicon: "public/favicon.ico"
  open-graph: true
  site-url: https://bedrock.engineer
  repo-url: https://github.com/bedrock-engineer/bedrock-web
  issue-url: https://github.com/bedrock-engineer/bedrock-ge/issues/new/choose
  repo-actions: [source, edit, issue]
  
  page-navigation: true
  bread-crumbs: true
  navbar:
    logo: "public/Bedrock.png"
    logo-alt: "Bedrock"
    left:
      - text: "Docs"
        href: docs/index.qmd
      - text: "Articles"
        href: articles.qmd
      # - text: "Community"
      #   href: community.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/bedrock-engineer/bedrock-ge/issues"
          - text: "Ask Bedrock a Question"
            icon: "chat-right-text"
            href: "https://github.com/orgs/bedrock-ge/discussions"
          - text: "Ask Speckle a Question"
            icon: "question-square-fill"
            href: "https://speckle.community/"
          # - text: "FAQ"
          #   icon: "question-circle"
          #   href: faq.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: github
        href: https://github.com/bedrock-engineer/bedrock-ge
        text: Bedrock's GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/bedrock-engineer
        text: Bedrock's LinkedIn
  sidebar:
    id: docs
    style: "floating"
    contents:
      - text: "Overview"
        href: docs/index.qmd
      - text: "Getting Started"
        href: docs/getting-started.qmd
      - section: "Tutorials"
        href: docs/tutorials/index.qmd
        contents: 
        - text: "AGS 3 to GIS"
          href: docs/tutorials/ags3_to_gis_and_speckle.ipynb
      - text: "How-To"
        href: docs/how-to/index.qmd
      - text: "Explanations"
        href: docs/explanations/index.qmd
      - section: "Reference"
        href: docs/reference/index.qmd
        contents:
        - text: "Glossary"
          href: docs/reference/glossary.qmd
        - text: "Sources"
          href: docs/reference/sources.qmd
    
  # page-footer: 
  #   right:
  #     - icon: github
  #       href: https://github.com/bedrock-gi/bedrock-gi
  #     - icon: linkedin
  #       href: https://www.linkedin.com/company/bedrock-gi/
  
  search:
    type: textbox
    show-item-context: true
  google-analytics:
    tracking-id: "G-JH73EGWYL6"
    anonymize-ip: true

execute:
  freeze: auto

language: 
  search-box-placeholder: Search
