project:
  type: website
  resources:
    - "public/**/*"

website:
  title: "Bedrock"
  description: "Bedrock, the Open Source Foundation for Geotechnical Engineering"
  image: "public/Bedrock_inCircle.png"
  favicon: "public/favicon.ico"
  open-graph: true
  site-url: https://bedrock.engineer
  repo-url: https://github.com/bedrock-engineer/bedrock-web
  issue-url: https://github.com/bedrock-engineer/bedrock-ge/issues/new/choose
  repo-actions: [source, edit, issue]
  page-navigation: true
  bread-crumbs: true
  navbar:
    logo: "public/Bedrock.png"
    logo-alt: "Bedrock"
    left:
      - text: "Documentation"
        href: docs/index.qmd
      - text: "Articles"
        href: articles.qmd
      # - text: "Community"
      #   href: community.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/bedrock-engineer/bedrock-ge/issues"
          - text: "Ask Bedrock a Question"
            icon: "chat-right-text"
            href: "https://github.com/orgs/bedrock-ge/discussions"
          - text: "Ask Speckle a Question"
            icon: "question-square-fill"
            href: "https://speckle.community/"
          # - text: "FAQ"
          #   icon: "question-circle"
          #   href: faq.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: github
        href: https://github.com/bedrock-engineer/bedrock-ge
        text: Bedrock's GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/bedrock-gi/
        text: Bedrock's LinkedIn
  page-footer: 
    right:
      - icon: github
        href: https://github.com/bedrock-engineer/bedrock-ge
      - icon: linkedin
        href: https://www.linkedin.com/company/bedrock-gi/
  search:
    type: textbox
    show-item-context: true
  google-analytics:
    tracking-id: "G-JH73EGWYL6"
    anonymize-ip: true

execute:
  freeze: auto

language: 
  search-box-placeholder: Search

# options specified here will apply to all pages in this folder
# https://quarto.org/docs/websites/website-navigation.html#side-navigation
# Sidebar Navigation goes into _quarto.yml, not here in the _metadata.yml
# quarto.org uses id's to identify sections

# website:
#   sidebar:
#     style: "floating"
#     contents:
#       - text: "Documentation"
#         href: index.qmd
#       - section: "Getting Started"
#         href: getting-started.qmd
#         contents:
#           - index.qmd
#           - basics-knitr.qmd
#           - basics-jupyter.qmd
#       - section: "Layout"
#         contents:
#           - layout.qmd
#           - layout-knitr.qmd
#           - layout-jupyter.qmd
#       - section: advanced.qmd
#         contents:
#           - raw-code.qmd
#           - custom-theme.qmd
#       - acknowlegment.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true
    jupyter: python3
    code-copy: true
    code-fold: true
    code-annotations: hover
