// @ts-check
import markdoc from "@astrojs/markdoc";
import { rehypeHeadingIds, unified } from "@astrojs/markdown-remark";
import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "astro/config";
import remarkDefinitionList from "remark-definition-list";
import starlightLinksValidator from "starlight-links-validator";
import starlightSidebarTopics from "starlight-sidebar-topics";
import sitemap from "@astrojs/sitemap";

const starlightConfig = {
  title: "Bedrock.engineer",
  plugins: [
    // The validator only learns pages from remark (.md/.mdx), so links that
    // target Markdoc (.mdoc) pages are falsely reported invalid and must be
    // excluded here.
    starlightLinksValidator({
      exclude: ["/docs/bedrock-ge/getting-started/"],
    }),
    // Each open-source package gets its own topic: a sidebar of its own plus a
    // switcher at the top of the sidebar. To add a package, create
    // src/content/docs/docs/<package>/ and add a topic entry here.
    starlightSidebarTopics([
      {
        label: "bedrock-ge",
        link: "/docs/bedrock-ge/getting-started/",
        icon: "seti:python",
        items: [
          {
            label: "Start Here",
            items: ["docs/bedrock-ge/getting-started"],
          },
          {
            label: "Explanation",
            items: [
              { autogenerate: { directory: "docs/bedrock-ge/explanation" } },
            ],
          },
          {
            label: "Guides",
            items: [{ autogenerate: { directory: "docs/bedrock-ge/guides" } }],
          },
          {
            label: "Reference",
            items: [
              { autogenerate: { directory: "docs/bedrock-ge/reference" } },
            ],
          },
          {
            label: "Resources",
            items: [
              { label: "Contributing", slug: "docs/bedrock-ge/contributing" },
              // { label: "Brand Assets", slug: "brand-assets" },
            ],
          },
        ],
      },
      {
        label: "cpt-anywidget",
        link: "/docs/cpt-anywidget/getting-started/",
        icon: "seti:python",
        items: [
          {
            label: "Start Here",
            items: ["docs/cpt-anywidget/getting-started"],
          },
          {
            label: "Reference",
            items: [
              { autogenerate: { directory: "docs/cpt-anywidget/reference" } },
            ],
          },
        ],
      },
    ], {
      // The /docs landing page lists all packages and belongs to no topic.
      exclude: ["/docs"],
    }),
  ],
  components: {
    ThemeSelect: "./src/components/ThemeToggle.astro",
  },
  // Adds per-page OG image meta tags for the cards generated by
  // src/pages/og/[...slug].ts.
  routeMiddleware: "./src/routeData.ts",
  customCss: ["./src/styles/custom.css"],
  lastUpdated: true,
  logo: {
    light: "./src/assets/bedrock.svg",
    dark: "./src/assets/bedrock.svg",
    replacesTitle: true,
  },
  favicon: "/bedrock.svg",
  editLink: {
    baseUrl: "https://github.com/bedrock-engineer/bedrock-web/edit/main/",
  },
  social: [
    {
      icon: "github",
      label: "GitHub",
      href: "https://github.com/bedrock-engineer/",
    },
    {
      icon: "linkedin",
      label: "LinkedIn",
      href: "https://www.linkedin.com/company/bedrock-engineer/",
    },
  ],
};

// https://astro.build/config
export default defineConfig({
  site: "https://bedrock.engineer",
  // NOTE: Enabling Astro's i18n config makes Starlight emit /nl/docs/* fallback
  // pages (English content under Dutch URLs). The marketing-page i18n below uses
  // file-based routing (src/pages/nl/*) + src/i18n/utils.ts instead, so this
  // stays off until docs i18n is tackled properly.
  // i18n: {
  //   defaultLocale: "en",
  //   locales: ["en", "nl"],
  //   routing: {
  //     prefixDefaultLocale: false,
  //   },
  // },
  prefetch: {
    prefetchAll: true,
  },
  integrations: [
    starlight(starlightConfig),
    mdx({
      optimize: true,
    }),
    markdoc({
      allowHTML: true,
    }),
    react({ experimentalReactChildren: true }),
    sitemap(),
  ],
  markdown: {
    processor: unified({
      remarkPlugins: [remarkDefinitionList],
      rehypePlugins: [rehypeHeadingIds],
    }),
  },
  vite: {
    plugins: [tailwindcss()],
  },
});
