// @ts-check
import markdoc from "@astrojs/markdoc";
import { rehypeHeadingIds, unified } from "@astrojs/markdown-remark";
import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";
import { remarkMarimo } from "@marimo-team/mdx-marimo/remark";
import { defineConfig } from "astro/config";
import remarkDefinitionList from "remark-definition-list";
import starlightLinksValidator from "starlight-links-validator";
import starlightSidebarTopics from "starlight-sidebar-topics";
import sitemap from "@astrojs/sitemap";

const starlightConfig = {
  title: "Bedrock.engineer",
  plugins: [
    // The validator only learns pages from remark (.md/.mdx), so links that
    // target Markdoc (.mdoc) pages are falsely reported invalid and must be
    // excluded here.
    starlightLinksValidator({
      exclude: ["/docs/bedrock-ge/getting-started/"],
    }),
    // Each open-source package gets its own topic: a sidebar of its own plus a
    // switcher at the top of the sidebar. To add a package, create
    // src/content/docs/docs/<package>/ and add a topic entry here.
    starlightSidebarTopics([
      {
        label: "bedrock-ge",
        link: "/docs/bedrock-ge/getting-started/",
        icon: "seti:python",
        items: [
          {
            label: "Start Here",
            items: ["docs/bedrock-ge/getting-started"],
          },
          {
            label: "Guides",
            items: [{ autogenerate: { directory: "docs/bedrock-ge/guides" } }],
          },
          {
            label: "Reference",
            items: [
              { autogenerate: { directory: "docs/bedrock-ge/reference" } },
            ],
          },
          {
            label: "Resources",
            items: [
              { label: "Contributing", slug: "docs/bedrock-ge/contributing" },
              // { label: "Brand Assets", slug: "brand-assets" },
            ],
          },
        ],
      },
      {
        label: "cpt-anywidget",
        link: "/docs/cpt-anywidget/getting-started/",
        icon: "seti:python",
        items: [
          {
            label: "Start Here",
            items: [
              "docs/cpt-anywidget/getting-started",
              "docs/cpt-anywidget/edit-layers",
            ],
          },
          {
            label: "Examples",
            items: [
              { autogenerate: { directory: "docs/cpt-anywidget/examples" } },
            ],
          },
          {
            label: "Reference",
            items: [
              { autogenerate: { directory: "docs/cpt-anywidget/reference" } },
            ],
          },
        ],
      },
      // Package-independent background reading (why geospatial, open
      // standards, etc.) shared by all packages.
      {
        label: "Concepts",
        link: "/docs/concepts/gi-to-geospatial/",
        icon: "open-book",
        items: [{ autogenerate: { directory: "docs/concepts" } }],
      },
    ], {
      // The /docs landing page lists all packages and belongs to no topic.
      exclude: ["/docs"],
    }),
  ],
  components: {
    ThemeSelect: "./src/components/ThemeToggle.astro",
  },
  // Adds per-page OG image meta tags for the cards generated by
  // src/pages/og/[...slug].ts.
  routeMiddleware: "./src/routeData.ts",
  customCss: ["./src/styles/custom.css", "@marimo-team/mdx-marimo/styles.css"],
  lastUpdated: true,
  logo: {
    light: "./src/assets/bedrock.svg",
    dark: "./src/assets/bedrock.svg",
    replacesTitle: true,
  },
  favicon: "/bedrock.svg",
  editLink: {
    baseUrl: "https://github.com/bedrock-engineer/bedrock-web/edit/main/",
  },
  social: [
    {
      icon: "github",
      label: "GitHub",
      href: "https://github.com/bedrock-engineer/",
    },
    {
      icon: "linkedin",
      label: "LinkedIn",
      href: "https://www.linkedin.com/company/bedrock-engineer/",
    },
  ],
};

// https://astro.build/config
export default defineConfig({
  site: "https://bedrock.engineer",
  // Package doc roots have no index page of their own; send them to the
  // topic's entry point so /docs/<package>/ doesn't 404.
  redirects: {
    "/docs/bedrock-ge": "/docs/bedrock-ge/getting-started/",
    "/docs/cpt-anywidget": "/docs/cpt-anywidget/getting-started/",
    // Explanation pages moved out of bedrock-ge into the package-independent
    // Concepts topic; the /explanation/* entries cover pre-restructure URLs.
    "/docs/bedrock-ge/explanation/gi-to-geospatial": "/docs/concepts/gi-to-geospatial/",
    "/docs/bedrock-ge/explanation/hierarchical-structure": "/docs/concepts/hierarchical-structure/",
    "/docs/bedrock-ge/explanation/concepts/open-source": "/docs/concepts/open-source/",
    "/docs/bedrock-ge/explanation/concepts/open-standards": "/docs/concepts/open-standards/",
    "/docs/bedrock-ge/explanation/concepts/spatial-reference-systems": "/docs/concepts/spatial-reference-systems/",
    "/explanation/gi-to-geospatial": "/docs/concepts/gi-to-geospatial/",
    "/explanation/hierarchical-structure": "/docs/concepts/hierarchical-structure/",
    "/explanation/concepts/open-source": "/docs/concepts/open-source/",
    "/explanation/concepts/open-standards": "/docs/concepts/open-standards/",
    "/explanation/concepts/spatial-reference-systems": "/docs/concepts/spatial-reference-systems/",
  },
  // NOTE: Enabling Astro's i18n config makes Starlight emit /nl/docs/* fallback
  // pages (English content under Dutch URLs). The marketing-page i18n below uses
  // file-based routing (src/pages/nl/*) + src/i18n/utils.ts instead, so this
  // stays off until docs i18n is tackled properly.
  // i18n: {
  //   defaultLocale: "en",
  //   locales: ["en", "nl"],
  //   routing: {
  //     prefixDefaultLocale: false,
  //   },
  // },
  prefetch: {
    prefetchAll: true,
  },
  integrations: [
    starlight(starlightConfig),
    mdx({
      optimize: true,
      // .mdx pages get the global markdown plugins plus marimo cell
      // compilation: ```python marimo fences become reactive Pyodide
      // islands (see the live cpt-anywidget examples). Plain .md pages
      // never contain marimo fences, so markdown.processor below stays
      // as is.
      processor: unified({
        remarkPlugins: [
          remarkDefinitionList,
          // the browser runtime is NOT injected here: MDX top-level
          // imports run at build time in Astro and never reach the
          // client. Pages with marimo cells render
          // src/components/MarimoRuntime.astro instead.
          remarkMarimo,
        ],
        rehypePlugins: [rehypeHeadingIds],
      }),
    }),
    markdoc({
      allowHTML: true,
    }),
    react({ experimentalReactChildren: true }),
    sitemap(),
  ],
  markdown: {
    processor: unified({
      remarkPlugins: [remarkDefinitionList],
      rehypePlugins: [rehypeHeadingIds],
    }),
  },
  vite: {
    plugins: [tailwindcss()],
  },
});
